
export interface RelatedContextItem {
  quote: string;
  category: string;
}

export interface FlashcardData {
  clozeText: string;
  originalQuote: string;
  relatedContext?: RelatedContextItem[]; // Mảng các đoạn trích nguyên văn và phân loại của chúng
  sourceHeading: string;
  sourceLesson: string;
  questionCategory: string;
  extraInfo?: string;
  cardId?: string; // Unique ID generated by AI for hierarchy
  parentId?: string | null; // ID of the parent card in the hierarchy
}

export interface ReviewableFlashcard extends FlashcardData {
    id: string; // Unique identifier
    dueDate: string; // ISO string date YYYY-MM-DD
    interval: number; // in days
    repetition: number;
    easeFactor: number; // a.k.a. EF
}

export type Specialty = 'Nội khoa' | 'Nhi khoa' | 'Sinh lý';

export type ClozeType = 'basic' | 'cluster' | 'overlapping' | 'hierarchical' | 'bidirectional' | 'disambiguation' | 'pedi_mindmap';

export interface GenerationResult {
  flashcards: FlashcardData[];
  report: string;
}

export interface CleaningResult {
    cleanedText: string;
    tableOfContents: string;
}

// --- Spaced Repetition for Essays Types ---

export interface EssayTopic {
  id: string;
  title: string;
  attempts: number;
  last_review: string | null;
  last_rating: number | null;
  next_due: string | null;
  interval_days: number;
  error_notes: string[];
}

export interface ReviewHistoryItem {
    topicId: string;
    review_date: string;

    rating: number;
    notes: string;
}

export interface SpacedRepetitionDB {
    topics: EssayTopic[];
    history: ReviewHistoryItem[];
}

export interface EssayGraderResult {
    gradingReport: string;
    srsRating: 0 | 1 | 2 | 3;
}

export interface ConversationTurn {
    role: 'user' | 'model';
    content: string;
}

export type ModelName = 'gemini-3-pro-preview' | 'gemini-2.5-pro' | 'gemini-2.5-flash';

export type ModelStageConfig = {
    model: ModelName;
    thinkMore: boolean;
};

export type ModelConfig = {
    clozeCleaning: ModelStageConfig;
    clozeAdvisor: ModelStageConfig;
    clozeGeneration: ModelStageConfig;
    essayCleaning: ModelStageConfig;
    essayInteraction: ModelStageConfig;
    essayGrading: ModelStageConfig;
};