


export interface RelatedContextItem {
  quote: string;
  category: string;
}

export interface FlashcardData {
  clozeText: string;
  originalQuote: string;
  relatedContext?: RelatedContextItem[]; // Mảng các đoạn trích nguyên văn và phân loại của chúng
  sourceHeading: string;
  sourceLesson: string;
  questionCategory: string;
  extraInfo?: string;
  cardId?: string; // Unique ID generated by AI for hierarchy
  parentId?: string | null; // ID of the parent card in the hierarchy
}

export interface ReviewableFlashcard extends FlashcardData {
    id: string; // Unique identifier
    dueDate: string; // ISO string date YYYY-MM-DD
    interval: number; // in days
    repetition: number;
    easeFactor: number; // a.k.a. EF
}

export type Specialty = 'Nội khoa' | 'Nhi khoa' | 'Sinh lý';

export type ClozeType = 'basic' | 'cluster' | 'overlapping' | 'hierarchical' | 'bidirectional' | 'disambiguation' | 'pedi_mindmap';

export interface GenerationResult {
  flashcards: FlashcardData[];
  report: string;
}

export interface CleaningResult {
    cleanedText: string;
    tableOfContents: string;
}

// --- Spaced Repetition for Essays Types ---

export interface EssayTopic {
  id: string;
  title: string;
  attempts: number;
  last_review: string | null;
  last_rating: number | null;
  next_due: string | null;
  interval_days: number;
  error_notes: string[];
}

export interface ReviewHistoryItem {
    topicId: string;
    review_date: string;

    rating: number;
    notes: string;
}

export interface SpacedRepetitionDB {
    topics: EssayTopic[];
    history: ReviewHistoryItem[];
}

export interface EssayGraderResult {
    gradingReport: string;
    srsRating: 0 | 1 | 2 | 3;
}

export interface ConversationTurn {
    role: 'user' | 'model';
    content: string;
}

export type ModelName = 'gemini-3-pro-preview' | 'gemini-2.5-pro' | 'gemini-2.5-flash' | 'gemini-3-flash-preview';

export type ModelStageConfig = {
    model: ModelName;
    thinkMore: boolean;
};

export type ModelConfig = {
    clozeCleaning: ModelStageConfig;
    clozeAdvisor: ModelStageConfig;
    clozeGeneration: ModelStageConfig;
    essayCleaning: ModelStageConfig;
    essayInteraction: ModelStageConfig;
    essayGrading: ModelStageConfig;
};

// --- MCQ Module Types ---

export type MCQMode = 'theory' | 'case';
export type MCQStage = 'setup' | 'generation' | 'audit' | 'finished';

export interface DifficultyWeights {
    easy: number;
    medium: number;
    hard: number;
    veryHard: number;
}

export interface MCQOptions {
    allowCrossSectionContext: boolean; // Cho phép dùng kiến thức từ phần khác trong bài
    allowExternalSources: boolean; // Cho phép dùng kiến thức ngoài (nguy hiểm, dễ hallucination)
}

export interface MCQCard {
    id: string;
    front: string; // Stem + Options
    options: string[]; // Raw options for structured display if needed
    correctOption: string; // e.g., 'A'
    back: string; // Compiled back side
    explanation: string;
    hint: string;
    originalQuote: string;
    sourceHeading: string;
    sourceLesson: string;
    questionCategory: string; // e.g. "Chẩn đoán", "Điều trị"
    difficultyTag: string; // e.g. "Dễ", "Trung bình", "Khó", "Rất khó"
    // Audit flags
    auditStatus?: 'pass' | 'fail' | 'warning';
    auditNotes?: string[];
}

export interface MCQJob {
    id: string;
    sectionTitle: string;
    sectionContent: string;
    status: 'queued' | 'running' | 'completed' | 'failed' | 'retrying';
    step: 'decompose' | 'generate' | 'evaluate' | 'decide' | 'done';
    result: MCQCard[];
    error?: string;
    retryCount: number;
    nextRetryTime?: number; // timestamp for backoff
    laneId?: number; // Which lane picked this up
}

export interface MCQLane {
    id: number;
    status: 'idle' | 'busy' | 'cooldown';
    currentJobId: string | null;
    cooldownEndsAt: number | null;
    errorCount: number;
}

export interface MCQGenerationResult {
    mcqs: MCQCard[];
    skippedReasons: string[];
    evaluationSummary: string;
}

export interface MCQAuditResult {
    auditReport: string;
    passedMCQs: MCQCard[];
    failedCount: number;
}

export type MCQConfig = {
    cleaning: ModelStageConfig;
    generation: ModelStageConfig;
    audit: ModelStageConfig;
};